### ISSUE TITLE
Not able to handle Conv-FC Dependency

### ISSUE THREAD

**Issue by Allhailankurgupta** [VainF/Torch-Pruning#2] opened 2020-03-08 07:42 UTC
I used the model
and I trained and pruned all conv layers with prob 0.3
as given in the code for l1 norm

I gave as input same as in the example for resnet
but it is not handling conv-fc dependency
```
class my_model(nn.Module):
  def __init__(self):
    super(my_model,self).__init__()
    self.conv1 = nn.Conv2d(3,16,kernel_size=3,stride=1,padding=1)
    self.conv2 = nn.Conv2d(16,32,kernel_size=3,stride=1,padding=1)
    self.conv3 = nn.Conv2d(32,64,kernel_size=3,stride=1,padding=1)
    self.pool = nn.MaxPool2d(2, 2)
    self.fc1 = nn.Linear(4*4*64,64)
    self.fc2 = nn.Linear(64,10)
  def forward(self,inp):
    ab = self.pool(F.relu(self.conv1(inp)))
    ab = self.pool(F.relu(self.conv2(ab)))
    ab = self.pool(F.relu(self.conv3(ab)))
    ab = ab.view(ab.shape[0],-1)
    ab = F.relu(self.fc1(ab))
    ab = F.relu(self.fc2(ab))
    return ab
    
```
I got this warning 
Warning: Unrecognized Conv-FC Dependency. Please handle the dependency manually
Warning: Unrecognized Conv-FC Dependency. Please handle the dependency manually

can you please help with this

**Comment by VainF** [comment] 2020-03-08 12:30
Hi @Allhailankurgupta, this warning was caused by a bug. I mistakenly used "if" rather than "elif" at [line 308](https://github.com/VainF/Torch-Pruning/blob/master/torch_pruning/dependency.py#L308). Now it has been fixed in the latest version.

**Comment by Allhailankurgupta** [comment] 2020-03-08 16:39
Glad you made the package and Glad you resolved the issue.
Thanks

**Comment by Allhailankurgupta** [comment] 2020-03-10 08:15
Can you please update it on pypi as well so that the updated version can be installed directly.

**Comment by VainF** [comment] 2020-03-10 08:54
> Can you please update it on pypi as well so that the updated version can be installed directly.

The package on pypi has been updated.

**Closed** 2020-03-26 14:25 UTC
